#!/bin/bash

usage () {
echo "
semi automatic RNA-Seq analysis

Usage: "$(basename "$0")" -c <config file name>

-c  Name of CSV file that contains the list of the softwares and the experimental groups.
-t  Max number of threads (default: all cores minus 2).
-u  Update conda dependencies.
"
exit -1
}

update () {

    mamba update -y -n base -c conda-forge -c anaconda -c bioconda -c defaults conda
    mamba update -y -n sara_dge -c conda-forge -c anaconda -c bioconda -c defaults --all
    mamba update -y -n sara_prep -c conda-forge -c anaconda -c bioconda -c defaults --all

exit -1
}

while getopts "hc:t:u" OPT; do
    case "$OPT" in
        h) usage;;
        c) SHEET="$OPTARG";;
        t) THREADS="$OPTARG";;
        u) update;;
    esac
done

SARA="$HOME"/sara

ID=$(basename "$SHEET" | awk -F. '{print $1}')

if [ -z "$THREADS" ]; then THREADS=$(lscpu | grep 'CPU(s):' | awk '{print $2}' | sed -n '1p' | awk '{print $1-2}'); fi

if [[ -z "$SHEET" ]]; then
    usage
else
    [ ! -d "$SARA"/ANALYSIS ] && mkdir "$SARA"/ANALYSIS
    [ ! -d "$SARA"/ANALYSIS/"$ID" ] && mkdir "$SARA"/ANALYSIS/"$ID" "$SARA"/ANALYSIS/"$ID"/ALIGN "$SARA"/ANALYSIS/"$ID"/CONCATENATED "$SARA"/ANALYSIS/"$ID"/DEG "$SARA"/ANALYSIS/"$ID"/INDEX "$SARA"/ANALYSIS/"$ID"/QC1 "$SARA"/ANALYSIS/"$ID"/QC2 "$SARA"/ANALYSIS/"$ID"/REFERENCE "$SARA"/ANALYSIS/"$ID"/TRIMMED
    echo "" && echo "Output path: "$SARA"/ANALYSIS/"$ID""
    echo "Log Analysis: "$SARA"/ANALYSIS/"$ID"/"$ID"_log_$(uname -n)_$(date +'%Y-%m-%d').txt"
    echo "" && echo "To display the log output in fulscreen: watch tail -n 20 "$SARA"/ANALYSIS/"$ID"/"$ID"_log_$(uname -n)_$(date +'%Y-%m-%d').txt"
fi

bg() {

    start=$(date +%s.%N)

    if [[ -z "$SHEET" ]]; then
        usage
    else
        source activate sara_prep
        if [[ ! $(ls -R "$SARA"/ANALYSIS/"$ID"/CONCATENATED 2>/dev/null | grep fastq) ]]; then
            find "$SARA"/RAW/"$ID" -type f -name '*.fastq.gz' -exec cp -vat "$SARA"/ANALYSIS/"$ID" {} +
                for i in $(find "$SARA"/ANALYSIS/"$ID" -type f -name "*.fastq.gz" | awk -F/ '{print $NF}' | awk -F'_L' '{print $1}' | sort -u); do
                    cat "$SARA"/ANALYSIS/"$ID"/"$i"_L00*_R1_001.fastq.gz > "$SARA"/ANALYSIS/"$ID"/CONCATENATED/"$i"_R1.fastq.gz
                    cat "$SARA"/ANALYSIS/"$ID"/"$i"_L00*_R2_001.fastq.gz > "$SARA"/ANALYSIS/"$ID"/CONCATENATED/"$i"_R2.fastq.gz
                done
            rm "$SARA"/ANALYSIS/"$ID"/*_001.fastq.gz
        fi
        if [[ ! $(ls -R "$SARA"/ANALYSIS/"$ID"/QC1 2>/dev/null | grep fastqc) ]]; then
            fastqc -t "$THREADS" $(find "$SARA"/RAW/"$ID" -type f -name "*.fastq.gz") -o "$SARA"/ANALYSIS/"$ID"/QC1
            multiqc -s -i ""$ID" RAW" -ip --no-data-dir -n "$SARA"/ANALYSIS/"$ID"/"$ID"_RAW_multiqc_report "$SARA"/ANALYSIS/"$ID"/QC1/*
        fi
        if [[ ! $(ls -R "$SARA"/ANALYSIS/"$ID"/QC2 2>/dev/null | grep fastqc) ]]; then
            fastqc -t "$THREADS" $(find "$SARA"/ANALYSIS/"$ID"/CONCATENATED -type f -name "*.fastq.gz") -o "$SARA"/ANALYSIS/"$ID"/QC2
            multiqc -s -i ""$ID" CONCATENATED" -ip --no-data-dir -n "$SARA"/ANALYSIS/"$ID"/"$ID"_CONCATENATED_multiqc_report "$SARA"/ANALYSIS/"$ID"/QC2/*
        fi
        TRIMM=$(cat "$SARA"/SHEETS/"$ID".csv | sed -n 1p | awk -F, '{print $1}')
        for i in $(find "$SARA"/ANALYSIS/"$ID"/CONCATENATED -type f -name "*.fastq.gz" | awk -F/ '{print $NF}' | awk -F"_S" '{print $1}' | sort -u); do
            if [[ "$TRIMM" == [Ff][Aa][Ss][Tt][Pp] ]]; then
                if [[ ! $(ls -R "$SARA"/ANALYSIS/"$ID"/TRIMMED 2>/dev/null | grep FP) ]]; then
                    fastp -w "$THREADS" -3 -5 -W 4 -M 25 -l 36 \
                        --in1 "$SARA"/ANALYSIS/"$ID"/CONCATENATED/"$i"*R1.fastq.gz \
                        --in2 "$SARA"/ANALYSIS/"$ID"/CONCATENATED/"$i"*R2.fastq.gz \
                        --out1 "$SARA"/ANALYSIS/"$ID"/TRIMMED/"$i"_R1_PAIRED_FP.fastq.gz \
                        --out2 "$SARA"/ANALYSIS/"$ID"/TRIMMED/"$i"_R2_PAIRED_FP.fastq.gz \
                        --unpaired1 "$SARA"/ANALYSIS/"$ID"/TRIMMED/"$i"_R1_UNPAIRED_FP.fastq.gz \
                        --unpaired2 "$SARA"/ANALYSIS/"$ID"/TRIMMED/"$i"_R2_UNPAIRED_FP.fastq.gz \
                        -j "$SARA"/ANALYSIS/"$ID"/TRIMMED/"$i"_fastp.json \
                        -h "$SARA"/ANALYSIS/"$ID"/TRIMMED/"$i"_fastp.html -R ""$i" fastp report"
                fi
            elif [[ "$TRIMM" == [Tt][Rr][Ii][Mm][Mm][Oo][Mm][Aa][Tt][Ii][Cc] ]]; then
                if [[ ! $(ls -R "$SARA"/ANALYSIS/"$ID"/TRIMMED 2>/dev/null | grep TM) ]]; then
                    trimmomatic PE -threads "$THREADS" -phred33 \
                        "$SARA"/ANALYSIS/"$ID"/CONCATENATED/"$i"*R1.fastq.gz \
                        "$SARA"/ANALYSIS/"$ID"/CONCATENATED/"$i"*R2.fastq.gz \
                        "$SARA"/ANALYSIS/"$ID"/TRIMMED/"$i"_R1_PAIRED_TM.fastq.gz \
                        "$SARA"/ANALYSIS/"$ID"/TRIMMED/"$i"_R1_UNPAIRED_TM.fastq.gz \
                        "$SARA"/ANALYSIS/"$ID"/TRIMMED/"$i"_R2_PAIRED_TM.fastq.gz \
                        "$SARA"/ANALYSIS/"$ID"/TRIMMED/"$i"_R2_UNPAIRED_TM.fastq.gz \
                        LEADING:3 TRAILING:3 SLIDINGWINDOW:4:25 MINLEN:36
                fi
            else
                echo "ATTENTION ON TRIMMING SETUP!!! Please check your CSV sheet. The name of the CSV file must corresponds the name of the library and contains comma-separated programs on the first line (i.e. 'trimm,mapping,count,deg). From the second line on, it must contain the list of samples and the condition, also separated by a comma [CTRL are controls; EXP are experimentals]."
            fi
        done
        REFERENCE=$(cat "$SARA"/SHEETS/"$ID".csv | sed -n 1p | awk -F, '{print $2}')
        echo "Downloading "$REFERENCE"..."
        if [[ "$REFERENCE" == [Gg][Rr][Cc][Hh][3][7] ]]; then # https://www.gencodegenes.org/human/release_39lift37.html
            if [[ ! $(ls -R "$SARA"/ANALYSIS/"$ID"/REFERENCE 2>/dev/null | grep "[Gg][Rr][Cc][Hh][3][7]") ]]; then
                wget http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/latest_release/GRCh37_mapping/GRCh37.primary_assembly.genome.fa.gz -q -O "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".fa.gz
                wget http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/latest_release/GRCh37_mapping/gencode.v39lift37.annotation.gtf.gz -q -O "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".gtf.gz
                gunzip "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".fa.gz
                gunzip "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".gtf.gz
            fi
        elif [[ "$REFERENCE" == [Gg][Rr][Cc][Hh][3][8] ]]; then # https://www.gencodegenes.org/human/
            if [[ ! $(ls -R "$SARA"/ANALYSIS/"$ID"/REFERENCE 2>/dev/null | grep "[Gg][Rr][Cc][Hh][3][8]") ]]; then
                wget http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/latest_release/GRCh38.p13.genome.fa.gz -q -O "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".fa.gz
                wget http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/latest_release/gencode.v39.annotation.gtf.gz -q -O "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".gtf.gz
                gunzip "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".fa.gz
                gunzip "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".gtf.gz
            fi
        elif [[ "$REFERENCE" == [Gg][Rr][Cc][Mm][3][9] ]]; then # https://www.gencodegenes.org/mouse/
            if [[ ! $(ls -R "$SARA"/ANALYSIS/"$ID"/REFERENCE 2>/dev/null | grep "[Gg][Rr][Cc][Hh][3][9]") ]]; then
                wget http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/latest_release/GRCm39.genome.fa.gz -q -O "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".fa.gz
                wget http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/latest_release/gencode.vM28.annotation.gtf.gz -q -O "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".gtf.gz
                gunzip "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".fa.gz
                gunzip "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".gtf.gz
            fi
        elif [[ "$REFERENCE" == [Cc][Hh][Mm][1][3] ]]; then # https://github.com/marbl/CHM13
            if [[ ! $(ls -R "$SARA"/ANALYSIS/"$ID"/REFERENCE 2>/dev/null | grep "[Cc][Hh][Mm][1][3]") ]]; then
                wget https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/chm13.draft_v1.1.fasta.gz -q -O "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".fa.gz
                wget https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/annotation/chm13.draft_v1.1.gene_annotation.v4.gff3.gz -q -O "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".gff3.gz
                gunzip "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".fa.gz
                gunzip "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".gff3.gz
            fi
        else
            echo "ATTENTION ON REFERENCE SETUP!!! Please check your CSV sheet. The name of the CSV file must corresponds the name of the library and contains comma-separated programs on the first line (i.e. 'trimm,mapping,count,deg). From the second line on, it must contain the list of samples and the condition, also separated by a comma [CTRL are controls; EXP are experimentals]."
        fi
    fi

    MAPPING=$(cat "$SARA"/SHEETS/"$ID".csv | sed -n 1p | awk -F, '{print $5}')
    if [[ "$MAPPING" == [Ss][Tt][Aa][Rr] ]]; then
        STAR --runThreadN "$THREADS" --runMode genomeGenerate --genomeDir "$SARA"/ANALYSIS/"$ID"/INDEX \
            --genomeFastaFiles "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".fa
        for i in $(find "$SARA"/ANALYSIS/"$ID"/TRIMMED -type f -name "*.fastq.gz" | awk -F/ '{print $NF}' | awk -F'_' '{print $1}' | sort -u); do
            STAR --runThreadN "$THREADS" --runMode alignReads --genomeDir "$SARA"/ANALYSIS/"$ID"/INDEX \
            --sjdbGTFfile "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".gtf \
            --readFilesIn "$SARA"/ANALYSIS/"$ID"/TRIMMED/"$i"_R1_PAIRED.fastq.gz \
            "$SARA"/ANALYSIS/"$ID"/TRIMMED/"$i"_R2_PAIRED.fastq.gz --readFilesCommand zcat \
            --outFileNamePrefix "$SARA"/ANALYSIS/"$ID"/ALIGN/"$i"_ --outSAMtype BAM Unsorted --outReadsUnmapped Fastx
        done
    fi

    COUNT=$(cat "$SARA"/SHEETS/"$ID".csv | sed -n 1p | awk -F, '{print $6}')
    if [[ "$COUNT" == [Ff][Ee][Aa][Tt][Uu][Rr][Ee][Cc][Oo][Uu][Nn][Tt][Ss] ]]; then
        featureCounts -a "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".gtf -o "$SARA"/ANALYSIS/"$ID"/"$ID"_counts.txt \
        -s 2 -G "$SARA"/ANALYSIS/"$ID"/REFERENCE/"$REFERENCE".fa -p --countReadPairs -C -T "$THREADS" \
        $(cat "$SARA"/SHEETS/"$ID".csv | sed '1d' | awk -F, -v ALIGN_PATH="$SARA"/ANALYSIS/"$ID"/ALIGN/ '$2~/EXP|CTRL/ \
            {print ALIGN_PATH $1"_Aligned.out.bam"}' | xargs)
    fi

    source activate r

    DEG=$(cat "$SARA"/SHEETS/"$ID".csv | sed -n 1p | awk -F, '{print $7}')
    if [[ "$DEG" == [Dd][Ee][Ss][Ee][Qq][2] ]]; then
        OUTPUT_PATH="$SARA"/ANALYSIS/"$ID"/DEG
        COUNTDATA="$SARA"/ANALYSIS/"$ID"/"$ID"_counts.txt
        HEADER=$(echo "$SARA"/ANALYSIS/"$ID"/ALIGN/ | tr / . | sed 's/.home/X.home/g')
        EXP_GROUP=$(cat "$SARA"/SHEETS/"$ID".csv | sed 1d | awk -F, '$2~/EXP/ {print $1}' | wc -l)
        CTRL_GROUP=$(cat "$SARA"/SHEETS/"$ID".csv | sed 1d | awk -F, '$2~/CTRL/ {print $1}' | wc -l)
        SMALL_GROUP=$(if [ $COUNTEXP -le $COUNTCTRL ]; then echo $COUNTEXP; else echo $COUNTCTRL;fi)
        Rscript "$SARA"/SCRIPTS/DESeq2.R $OUTPUT_PATH $COUNTDATA $HEADER $EXP_GROUP $CTRL_GROUP $SMALL_GROUP
    fi

    end=$(date +%s.%N)

    runtime=$(python -c "print(${end} - ${start})")

    echo "" && echo "Done. The runtime was "$runtime" seconds."

}

bg &>>"$SARA"/ANALYSIS/"$ID"/"$ID"_log_$(uname -n)_$(date +'%Y-%m-%d').txt &

exit 0
